import Image from 'next/image'
import { notFound } from 'next/navigation'
import { Heart, MapPin, Share2, ShieldCheck, Star } from 'lucide-react'
import { products, formatPrice } from '@/lib/catalog'
import { ProductActions } from '@/components/product-actions'
import { ProductCard } from '@/components/product-card'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'
import { Button } from '@/components/ui/button'

export function generateStaticParams(){ return products.map(({slug})=>({slug})) }
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const product=products.find((item)=>item.slug===slug); if(!product) notFound(); return <div className="site-container section-space">
  <div className="grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:gap-16"><div className="grid grid-cols-2 gap-3"><div className="relative col-span-2 aspect-[4/5] overflow-hidden bg-muted"><Image src={product.image} alt={product.name} fill priority className="object-cover" sizes="(max-width:1024px) 100vw, 55vw" /></div><div className="relative aspect-[4/5] overflow-hidden"><Image src={product.altImage} alt={`${product.name} editorial view`} fill className="object-cover" /></div><div className="relative aspect-[4/5] overflow-hidden"><Image src="/images/silk-editorial.png" alt="Textile detail" fill className="object-cover" /></div></div>
  <div className="lg:sticky lg:top-44 lg:self-start"><p className="text-xs font-semibold uppercase tracking-[.25em] text-primary">{product.fabric}</p><h1 className="mt-3 text-5xl leading-tight">{product.name}</h1><div className="mt-4 flex items-center gap-2 text-sm"><Star className="size-4 fill-accent text-accent" /> {product.rating} · 38 reviews</div><div className="mt-6 flex items-baseline gap-3"><span className="font-price text-2xl">{formatPrice(product.price)}</span>{product.comparePrice && <span className="text-muted-foreground line-through">{formatPrice(product.comparePrice)}</span>}</div><p className="mt-6 leading-relaxed text-muted-foreground">{product.story}</p><div className="mt-8"><p className="mb-3 text-xs font-semibold uppercase tracking-widest">Select color</p><div className="flex gap-3"><button className="size-10 rounded-full border-2 border-primary bg-primary" aria-label={product.color}/><button className="size-10 rounded-full border border-border bg-accent" aria-label="Gold" /></div></div><ProductActions slug={product.slug} />
  <div className="mt-6 grid grid-cols-2 gap-4 border-y border-border py-5 text-xs"><span className="flex items-center gap-2"><ShieldCheck className="size-5" />Authenticity assured</span><span className="flex items-center gap-2"><MapPin className="size-5" />Mock delivery estimator</span></div>
  <Accordion><AccordionItem value="craft"><AccordionTrigger>Fabric & craftsmanship</AccordionTrigger><AccordionContent>Handwoven {product.fabric} finished by master artisans. Minor variations are a mark of the maker.</AccordionContent></AccordionItem><AccordionItem value="care"><AccordionTrigger>Care instructions</AccordionTrigger><AccordionContent>Dry clean only. Store wrapped in muslin and air periodically.</AccordionContent></AccordionItem><AccordionItem value="shipping"><AccordionTrigger>Shipping & returns</AccordionTrigger><AccordionContent>UI preview only. Shipping and returns will be connected in Phase 2.</AccordionContent></AccordionItem></Accordion></div></div>
  <section className="pt-24"><h2 className="mb-10 text-center text-5xl">Pair it with</h2><div className="grid grid-cols-2 gap-5 md:grid-cols-4">{products.filter((p)=>p.slug!==slug).slice(0,4).map((p)=><ProductCard key={p.slug} product={p}/>)}</div></section>
</div> }
